export const artisticFonts = [
  { font: "'Pacifico', cursive", size: "2rem" },
  { font: "'Lobster', cursive", size: "2rem" },
  { font: "'Dancing Script', cursive", size: "2rem" },
  { font: "'Great Vibes', cursive", size: "2rem" },
  { font: "'Satisfy', cursive", size: "2rem" },
  { font: "'Shadows Into Light', cursive", size: "2rem" },
  { font: "'Amatic SC', cursive", size: "2rem" },
  { font: "'Indie Flower', cursive", size: "2rem" },
  { font: "'Italianno', cursive", size: "2rem" },
  { font: "'Alex Brush', cursive", size: "2rem" },
  { font: "'Niconne', cursive", size: "2rem" },
  { font: "'Cookie', cursive", size: "2rem" },
  { font: "'Parisienne', cursive", size: "2rem" },
  { font: "'Yellowtail', cursive", size: "2rem" },
  { font: "'Allura', cursive", size: "2rem" },
  { font: "'Tangerine', cursive", size: "2rem" },
  { font: "'Herr Von Muellerhoff', cursive", size: "2rem" },
  { font: "'Sacramento', cursive", size: "2rem" },
  { font: "'Marck Script', cursive", size: "2rem" },
  { font: "'Bad Script', cursive", size: "2rem" },
  { font: "'Petit Formal Script', cursive", size: "2rem" },
  { font: "'Ephesis', cursive", size: "2rem" },
  { font: "'Gwendolyn', cursive", size: "2rem" },
  { font: "'Ms Madi', cursive", size: "2rem" },
  { font: "'Qwigley', cursive", size: "2rem" },
  { font: "'Seaweed Script', cursive", size: "2rem" },
  { font: "'Yesteryear', cursive", size: "2rem" },
  { font: "'Zeyada', cursive", size: "2rem" }
];
